export const commitTypes = [
    { label: 'feat', emoji: '✨', description: 'New feature' },
    { label: 'fix', emoji: '🐛', description: 'Bugfix' },
    { label: 'docs', emoji: '📚', description: 'Documentation changes' },
    { label: 'test', emoji: '🧪', description: 'Test changes' },
    { label: 'build', emoji: '👷', description: 'Build and dependency changes' },
    { label: 'perf', emoji: '⚡', description: 'Performance-related changes' },
    { label: 'style', emoji: '💅', description: 'Code style changes' },
    { label: 'refactor', emoji: '🔨', description: 'Code refactoring' },
    { label: 'chore', emoji: '🔧', description: 'Task and configuration updates' },
    { label: 'ci', emoji: '🚀', description: 'Continuous integration changes' },
    { label: 'merge', emoji: '🔀', description: 'Branch merging' },
    { label: 'revert', emoji: '⏪', description: 'Reverting a change' },
    { label: 'release', emoji: '📦', description: 'Version release' },
    { label: 'security', emoji: '🔒', description: 'Security fixes' },
    { label: 'dependency', emoji: '📦', description: 'Dependency updates' },
    { label: 'wip', emoji: '🚧', description: 'Work in progress' },
    { label: 'config', emoji: '⚙️', description: 'Configuration changes' },
    { label: 'accessibility', emoji: '♿', description: 'Accessibility improvements' },
    { label: 'comments', emoji: '💡', description: 'Adding comments' },
    { label: 'initial commit', emoji: '🎉', description: 'Initial commit' },
    { label: 'deploy', emoji: '🚀', description: 'Deployment' },
    { label: 'animations and transitions', emoji: '💫', description: 'Animations and transitions' },
    { label: 'moving/renaming', emoji: '🚚', description: 'Moving/Renaming' },
    { label: 'package.json in JS', emoji: '📦', description: 'Package.json update (JavaScript)' },
    { label: 'responsiveness', emoji: '📱', description: 'Responsiveness improvements' },
    { label: 'version tag', emoji: '🔖', description: 'Creating a version tag' },
    { label: 'approval test', emoji: '✔️', description: 'Approval test' },
    { label: 'text', emoji: '📝', description: 'Text update' },
    { label: 'typing', emoji: '🏷️', description: 'Typing update' },
    { label: 'error handling', emoji: '🥅', description: 'Error handling' },
];